Todo
Pascazio/entryJS pull request #6
Opened 2023-11-02 18:16 UTC by ImZioTonio

Add simple operation

2023-11-02 18:24 UTC, Pascazio requested changes
Ci sono delle modifiche da perfezionare. Sono presenti nei commenti della PR.

2023-11-02 18:24 UTC, Pascazio commented on src/library.js
nei console.log, rimuovere gli apici ( ' ) ed utilizzare il carattere corretto ( è )

2023-11-02 18:24 UTC, Pascazio commented on src/library.js
Per quale motivo esportiamo sum, sott, molt e div?

2023-11-04 10:29 UTC, ImZioTonio commented on src/library.js
Ho provato a rimuovere gli apici singoli ma non funziona, va in errore

2023-11-04 10:29 UTC, ImZioTonio commented on src/library.js
Ho motificato richiamando ogni funzione a sè. Risolto anche il problema del NaN

2023-11-06 08:26 UTC, Pascazio approved these changes

2023-11-06 08:37 UTC, merged